package mx.unam.ciencias.is.mapa.modelo;
// Generated 26-ene-2019 22:09:27 by Hibernate Tools 4.3.1



/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int idmarcador;
     private Double longitud;
     private Double latitud;
     private Integer usuarioid;

    public Marcador() {
    }

	
    public Marcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public Marcador(int idmarcador, Double longitud, Double latitud, Integer usuarioid) {
       this.idmarcador = idmarcador;
       this.longitud = longitud;
       this.latitud = latitud;
       this.usuarioid = usuarioid;
    }
   
    public int getIdmarcador() {
        return this.idmarcador;
    }
    
    public void setIdmarcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    public Integer getUsuarioid() {
        return this.usuarioid;
    }
    
    public void setUsuarioid(Integer usuarioid) {
        this.usuarioid = usuarioid;
    }




}


